<?php

/**
* Implemetation hook_menu
**/
function vacantes_menu() {
  $items = array();
  /*
  $items['carrera/vacantes'] = array(
    'title' => t('Vacantes'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('vacantes_form'),
    'access arguments' => array('access content'),
  );*/
  return $items;
}

/**
* Aplictation form content
**/
function crea_formulario() {
  $cabeza = '<div class="t-vacantehead"><h1>Vacantes</h1></div>';
  $formulario = drupal_get_form('vacantes_form');
  $foot = '<div class="t-vacantefoot">Enviar Aplicaciones</div>';
  $completo = $cabeza.$formulario.$foot;
  return $completo;
}
function vacantes_form() {
  $cantidad = 0;
  drupal_add_css(drupal_get_path('module', 'vacantes') . '/style/jquery.jscrollpane.css', array('group' => CSS_DEFAULT, 'every_page' => FALSE));
  drupal_add_css(drupal_get_path('module', 'vacantes') . '/style/vacantes.css', array('group' => CSS_DEFAULT, 'every_page' => FALSE));
  drupal_add_js(drupal_get_path('module', 'vacantes') . '/js/jquery.mousewheel.js', array('group' => JS_DEFAULT, 'every_page' => FALSE));
  drupal_add_js(drupal_get_path('module', 'vacantes') . '/js/jquery.jscrollpane.js', array('group' => JS_DEFAULT, 'every_page' => FALSE));
  $nodes = node_load_multiple(array(), array('type' => array('vacantes')));
  $form["header"] = array(
    '#type' => 'hidden',
    '#prefix' => '<div class="t-vacantehead"><h1>Vacantes</h1></div>',
  );
  if(sizeof($nodes) > 0){
    $form["principio"] = array(
        '#type' => 'hidden',
        '#prefix' => '<div class="scroll-pane">',
    );
    foreach ($nodes as $key => $value) {
      if ($value->status > 0 ) {
        $form["fileset_$value->nid"] = array(
            '#type' => 'fieldset',
        );
        $form["fileset_$value->nid"]["title_$value->nid"] = array(
          '#markup' => $value->title,
          '#prefix' => '<h2 class="title_vacantes">',
          '#suffix' => '</h2>',
        );
        $form["fileset_$value->nid"]["date_$value->nid"] = array(
          '#markup' => t('Actualizado fecha', array('fecha' => format_date($value->changed, 'custom', 'd / M / Y'))),
          '#prefix' => '<h2 class="date_vacantes">',
          '#suffix' => '</h2>',
        );
        $form["fileset_$value->nid"]["body_$value->nid"] = array(
          '#markup' => substr($value->body['und'][0]['safe_summary'], 0, 300),
          '#prefix' => '<div class="cuerpor_vacantes">',
          '#suffix' => '</div>',
        );
        $form["fileset_$value->nid"]["select_$value->nid"] = array(
          '#type' => 'checkbox',
          '#title' => t('Aplicar a esta vacante'),
          '#class' => array('t-aplica'),
        );
        $form["fileset_$value->nid"]["more_$value->nid"] = array(
          '#markup' => l(t("Ver más"), "node/$value->nid"),
          '#prefix' => '<div class="more_vacantes">',
          '#suffix' => '</div>',
        );
        $cantidad ++;
      }
    }
    if ($cantidad == 0) {
      $form['empty'] = array(
        '#type' => 'item',
        '#title' => t('En el Momento no hay Vacantes disponibles'),
      );
      $form["fin"] = array(
        '#type' => 'hidden',
        '#suffix' => '</div>',
      );
    }
    else{
      $form["fin"] = array(
        '#type' => 'hidden',
        '#suffix' => '</div>',
      );
      $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Enviar todas las aplicaciones')
      );
    }
  }

  else{
    $form['empty'] = array(
      '#type' => 'item',
      '#title' => t('En el Momento no hay Vacantes disponibles'),
    );
  }

  return $form;
}

function vacantes_form_validate($form, &$form_state) {
  $clave   = 'select_';
  $nids = array();
  foreach ($form_state['values'] as $key => $value) {
    if(strpos($key, $clave) !== FALSE ) {
      if($value == 1) {
        $nids[] = str_replace($clave, '', $key);
      }
    }
  }
  if(empty($nids)){
    form_set_error('campos');
    drupal_set_message( 'Para continuar debes seleccionar al menos una vacante', 'warning');
  }
}

/**
* Form Submit
**/

function vacantes_form_submit($form, &$form_state) {
  global $user;
  $user_loaded = user_load($user->uid);
  $first_name = '';
  $last_name = '';
  if (isset($user_loaded->field_user_firstname)) {
   $first_name = $user_loaded->field_user_firstname['und'][0]['safe_value'];
  }
  if (isset($user_loaded->field_user_lastname )) {
   $last_name = $user_loaded->field_user_lastname ['und'][0]['safe_value'];
  }
  $clave   = 'select_';
  $nids = array();
  foreach ($form_state['values'] as $key => $value) {

    if(strpos($key, $clave) !== FALSE ) {
      if($value == 1) {
        $nids[] = node_get_title(str_replace($clave, '', $key));
      }
    }
  }
  drupal_goto('node/2908', array('query' =>
    array('vacantes' => implode("-", $nids) , 'fname' => $first_name, 'lname' => $last_name )));
}

function node_get_title($nid) {
 $result = db_select('node', 'n')
    ->fields('n')
    ->condition('nid', $nid)
    ->execute()
    ->fetchAssoc();
  return $result['title'];
}

/**
* Implemetation hook_node_view
**/
function vacantes_node_view($node, $view_mode, $langcode) {
  if ($view_mode == 'full' && $node->type == 'vacantes') {
    drupal_add_css(drupal_get_path('module', 'vacantes') . '/style/vacantes.css', array('group' => CSS_DEFAULT, 'every_page' => FALSE));
  }
}
